=== computer-agents/agent-studio/desktop_env/eval/examples/envs/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "additionalProperties": false,
    "required": ["applications", "applications_settings", "intent", "environments"],
    "properties": {
        "applications": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "applications_settings": {
            "type": "object"
        },
        "intent": {
            "type": "string"
        },
        "environments": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "object"
                }
            }
        }
    }
}

=== computer-agents/agent-studio/desktop_env/eval/examples/envs/filesystem_env.json
{
    "applications": ["filesystem"],
    "applications_settings": {
        "filesystem": {
        }
    },
    "intent": "Add some introductions to this environment",
    "environments": {
        "filesystem": [
            {
                "mkdir": {
                    "path": "tmp"
                }
            },
            {
                "create_file": {
                    "path": "tmp/test.txt",
                    "content": "Hello World!"
                }
            },
            {
                "chmod": {
                    "path": "tmp/test.txt",
                    "mode": "0o775"
                }
            },
            {
                "chmod": {
                    "path": "tmp",
                    "mode": "0o644"
                }
            }
        ]
    }
}
